parameters:
    telegram.bot_token: '%env(TELEGRAM_BOT_TOKEN)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true

    # Active l'autowiring et l'autoconfiguration pour tous les services dans src/
    App\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Service TelegramService
    App\Service\TelegramService:
        arguments:
            $httpClient: '@http_client'      # Injection de HttpClientInterface
            $params: '@parameter_bag'        # Injection de ParameterBagInterface


    # Uncomment this block to activate the command
    # App\Command\TelegramConsumerCommand:
    #     arguments:
    #         $telegramService: '@App\Service\TelegramService'
    #         $cache: '@cache.adapter.redis'  # Injecte le service Redis
    #     tags:
    #         - { name: 'console.command' }

  
